### ISSUE TITLE
Spam from log call

### ISSUE THREAD

**Issue by springjools** [springjools/deluge-autoremoveplus#18]
Did something change in python 3.8 in terms of the log module? I'm getting a lot of spam like this:

https://pastebin.com/0nRCvjCa

AFAICT it's the log module that's failing. Just posting this in case someone happens to be aware of this as well.

**Comment by mhertz** [comment]
Deluge 2.0.3 with py38 needs backported commit from develop branch: https://git.deluge-torrent.org/deluge/commit/?h=develop&id=351664ec071daa04161577c6a1c949ed0f2c3206

**Comment by springjools** [comment]
Hmmm, I get the same error also with Deluge 2.04.dev24, but I'll close this as it's not related to this plugin.
https://pastebin.com/2pMqtdat

**Comment by mhertz** [comment]
I'm sorry, I thought it was related, but seemingly not.

**Comment by springjools** [comment]
Yeah Yeah it's related, but either I screwed up somewhere or the fix is needed in more places. Not sure what's the relation with the findCaller function and the _findCaller one.

**Comment by mhertz** [comment]
Are you using latest twisted i.e 20.3.0? https://github.com/twisted/twisted/commit/c0ce0d77be9152a8a3645c5bddb6e2f9cc56d98f

**Comment by springjools** [comment]
No, I'm using 18.9.0. Maybe that's why. Thanks.

**Comment by springjools** [comment]
@mhertz Upgrading to twisted 20.3.0 resolved the issue, but I had to do it forcefully on Debian 10 with pip3 install twisted==20.3.0

**Comment by mhertz** [comment]
Glad to hear it. Strange, pip has always for me installed latest version when not forcing otherwise, though i'm not on debian(arch/win10-VM for deluge2), though you got it fixed is only thing mattering of-course. I still find it strange that the deluge fix doesn't fix this, as per your post in that #3327 deluge ticket, though probably makes sence anyway, as only deluge got "fixed" in that commit, but will still forward messages from components "unfixed" im guessing, like twisted in this case, though don't know much about such honestly. Thanks again for your work, and let me know if I can help test something for you on GTKUI or windows or whatever(e.g. forward error messages from log - I read previously you haden't GTKUI available. EDIT: Just in case if still the case, then this is error from gtkui when enabling plugin: https://pastebin.com/TwBq0eq1 ).

**Comment by springjools** [comment]
Thank you yourself  :)
