### ISSUE TITLE
Release 0.6.15

### ISSUE THREAD

**Issue by Groodles** [springjools/deluge-autoremoveplus#23]
Upgraded from 0.6.14 to 0.6.15 and the plugin would not load... at least it no longer appeared in the WebUI.

Reverted to 0.6.14 and it's back and working again.

**Comment by springjools** [comment]
Anything in the logs? Did you reload deluge web-ui with F5?

**Comment by Groodles** [comment]
I did reload the WebUI with CTRL + F5 but this made no difference.  The rest of the WebUI presented normally and all other plugins could be enabled/disabled in the Options dialog.  However, the AutoRemovePlus plugin was not visible for selection and therefore could not be enabled via the WebUI.

I dont have any logs.

**Comment by springjools** [comment]
Well it's difficult to fix this without more information. I'll leave this open in case somebody has the same issue in the future.

**Comment by Groodles** [comment]
Let me install 0.6.15 again... I'll run deluged with logging and see what comes out.

**Comment by Groodles** [comment]
Ok, so I tried it again.  I've put the 0.6.15 egg in the /.config/deluge/plugins folder (where the 0.6.14 version is installed).  I temporarily moved 0.6.14 to another location and restarted deluged with logging enabled and extracted this from the log file.

`[WARNING ][deluge.pluginmanagerbase      :132 ] Cannot enable non-existant plugin AutoRemovePlus`

I did not built the egg myself, I just downloaded it from the release page.  Is the egg built correctly?

**Comment by mhertz** [comment]
The issue is that you have another version of python3 installed than v3.8.x. Rename the 8 to 7 or 6, depending on py3 version installed(python3 - -version), or simply remove the part about python and version, like it was previous.

Springjools, Cas stated once in deluge2 changelog that this wasent an issue anymore(going by py version in name to determine if should be enabled or not, like as before), but that isn't the case, so must be some mistake in that code, or was reverted later I dunno. Plugins often has several versions for the py versions on there release page, which you can just rename if will provide yourself, but probably better to just remove the py version from filename entirely, like was before when you just zipped up files and didn't use setup.py for building egg. Without one of these two suggestions incorporated, then tickets like this will increase I'm sure.

**Comment by springjools** [comment]
Ok, thanks. I actually built the 0.6.15 version by using the python setup build and /install commands. before I just zipped the files into the folder and changed the name to .egg.

I also recall reading that comment and that's why i stopped using the py version in the name.

**Comment by Groodles** [comment]
@mhertz So do I need to change something to make it work for me?

**Comment by mhertz** [comment]
Yes. As per my previous post, rename the filename of plugin egg. Either remove py3.8 part, or change the 8 to 7 or 6, depending on python3 version installed(python3 --version) so they match.

**Comment by Groodles** [comment]
@mhertz Ahhhh.  I didn't understand your previous post.  Thanks for clarification.

@springjools With the .egg renamed, it's now working again.
